#!/usr/bin/env python3
from __future__ import annotations

import argparse
from common import PUBLIC_REPO, UPSTREAM_REPO, append_receipt, gh_api, load_json, now_iso, run_dir


def body_for(report: dict, tag: str) -> str:
    return f"""## Summary
Validated tester report from HeraldLab OpenclawQA for `{tag}`.

## Source report
- Public QA repo: https://github.com/{PUBLIC_REPO}/tree/main/runs/{tag}
- Tester report: {report.get('url')}

## Steps to reproduce
NOT_ENOUGH_INFO — see tester report for raw reproduction details.

## Expected behavior
NOT_ENOUGH_INFO

## Actual behavior
NOT_ENOUGH_INFO

## Environment
- OpenClaw version/tag: `{tag}`
- OS/platform: NOT_ENOUGH_INFO
- Install method: NOT_ENOUGH_INFO

## Evidence
See tester report linked above. Do not copy private logs/secrets into this issue.

## Notes
Generated by OpenclawQA upstream filing workflow. Human review recommended before acting.
"""


def main() -> int:
    ap = argparse.ArgumentParser(description="Create or dry-run upstream OpenClaw issues from validated tester reports")
    ap.add_argument("tag")
    ap.add_argument("--dry-run", action="store_true", default=False)
    ap.add_argument("--live", action="store_true", help="Actually file upstream issues. Use carefully.")
    args = ap.parse_args()
    tag = args.tag
    rd = run_dir(tag)
    status = load_json(rd / "tester-status.json", {}) or {}
    dry = []
    filed = []
    for report in status.get("reports", []):
        labels = set(report.get("labels") or [])
        eligible = "status:validated" in labels or "severity:blocker" in labels or "beta-blocker" in labels
        title_prefix = "Beta blocker" if ("severity:blocker" in labels or "beta-blocker" in labels) else "QA bug"
        title = f"{title_prefix}: {report.get('title', 'NOT_ENOUGH_INFO')[:160]}"
        body = body_for(report, tag)
        item = {"source_report": report.get("url"), "title": title, "body": body, "eligible": eligible}
        if args.live and eligible:
            created = gh_api(f"/repos/{UPSTREAM_REPO}/issues", method="POST", token_required=True, data={"title": title, "body": body, "labels": ["beta-blocker"] if title_prefix == "Beta blocker" else []})
            item["created_url"] = created.get("html_url")
            filed.append(item)
        else:
            dry.append(item)
    receipt = {"tag": tag, "generated_at": now_iso(), "dry_run": not args.live, "upstream_repo": UPSTREAM_REPO, "dry_run_items": dry, "filed_items": filed}
    append_receipt(tag, "issue-file-results.json", receipt)
    lines = [f"# Upstream Issues Filed — `{tag}`\n\n", f"Generated: `{receipt['generated_at']}`\n\n"]
    if args.live:
        lines.append(f"Live filing mode. Created: **{len(filed)}**\n\n")
        for item in filed:
            lines.append(f"- [{item['title']}]({item.get('created_url')}) from {item.get('source_report')}\n")
    else:
        lines.append("Dry-run mode. No upstream OpenClaw issues were created.\n\n")
        lines.append(f"Dry-run candidates: **{len(dry)}**\n\n")
        for item in dry:
            lines.append(f"## {item['title']}\n\nEligible for live filing: `{item['eligible']}`\n\nSource: {item.get('source_report')}\n\n```markdown\n{item['body']}\n```\n\n")
    (rd / "upstream-issues-filed.md").write_text("".join(lines), encoding="utf-8")
    print(f"dry_run_items={len(dry)} filed_items={len(filed)}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
